# -*- coding: utf-8 -*-
"""Textele GDH (generat din copy_gdh.py) — vezi build_gdh.py."""

BRAND = 'GDH'
BRAND_FULL = 'Global Distribution Holdings'
SITE_NAME = 'GDH — Global Distribution Holdings'

# Adresa publică. Un singur loc de schimbat dacă se mută domeniul: de aici se
# construiesc og:url, canonical și adresa absolută a imaginii de partajare
# (WhatsApp/Discord nu acceptă cale relativă la og:image).
SITE_URL = 'https://gdh-group.com'

OG_ALT = ('GDH — Global Distribution Holdings: warehousing, order fulfilment '
          'and route delivery')

TITLES = {'index.html': ('GDH — Global Distribution Holdings | Product Distribution & Fulfilment', 'GDH distributes consumer, retail and industrial products end to end — national warehousing, order fulfilment, route delivery and merchandising under one accountable team.'), 'service.html': ('Distribution Services | GDH', 'Warehousing, order fulfilment, route-to-market delivery, cold chain and reverse logistics — services that run on their own or as one connected distribution programme.'), 'case-study.html': ('Client Programmes | GDH', 'How retail, grocery, pharmacy and industrial brands moved their products faster with GDH distribution programmes.'), 'blog.html': ('Distribution Insights | GDH', 'Practical guidance on stock coverage, fulfilment accuracy, route planning and retail execution from the GDH distribution team.'), 'contact.html': ('Request a Distribution Quote | GDH', 'Tell us what you distribute, where it has to reach and how often — we will come back with a coverage plan and pricing.')}

# noduri de text potrivite exact (dupa strip)
EXACT = [
    ('Frevanta – Webflow HTML Website Template',
     'GDH — Global Distribution Holdings'),
    ('Freight & Logistics Insights Frevanta',
     'Distribution Insights from GDH'),
    ('Why choose Frevanta',
     'Why distributors choose GDH'),
    ('1. What services does Frevanta provide?',
     '1. What does GDH actually distribute?'),
    ('3. Does Frevanta handle international shipments?',
     '3. Do you cover the whole country, or only major cities?'),
    ('4. Can I use only one Frevanta service?',
     '4. Can I use only warehousing, without delivery?'),
    ('“Before Frevanta, we spent hours contacting separate carriers and warehouses for shipment updates. Now we have one team, one plan, and a much clearer view of every order in motion.”',
     '“Before GDH we chased three warehouses and two carriers just to learn where our stock was. Now one team runs storage, picking and delivery, and we see every order in one place.”'),
    ('“Working with Frevanta completely transformed the way we manage shipments. Everything is organized in one place, saving our team valuable time while giving us complete confidence in every delivery.”',
     '“GDH changed the way we get product to shelf. Stock, orders and routes sit in one place, our team saves hours every week, and store managers stop calling us about missing deliveries.”'),
    ('“Frevanta helped us replace manual coordination with a seamless workflow. Our team communicates better, responds faster, and keeps every shipment on schedule.”',
     '“GDH replaced our spreadsheets with a proper distribution workflow. Replenishment is planned, orders leave on time, and we finally know our real cost per drop.”'),
    ('“Tracking shipments across different providers was frustrating and time-consuming. Now everything is organized in one system, helping us save time while improving delivery accuracy every day.”',
     '“Tracking stock across separate providers was a daily guessing game. Everything now sits in one system, which saved us time and pushed our delivery accuracy well above where it was.”'),
    ('Frevanta provides global freight forwarding and logistics across air, ocean, road and rail, with warehousing, customs clearance and last-mile delivery.',
     'GDH is a product distribution company: national warehousing, order fulfilment, route delivery and retail execution for consumer, grocery, pharmacy and industrial brands.'),
    ('Frevanta coordinates air, ocean, road, and rail freight with warehousing, customs clearance, and last-mile delivery — giving your business one team, one plan, and clear visibility from pickup to destination.',
     'GDH stores, picks, packs and delivers your products to retailers, pharmacies, HoReCa and end customers — one team, one plan, and clear visibility from our warehouse door to the shelf.'),
    ('© 2026 Frevanta. All Rights Reserved.',
     '© 2026 GDH — Global Distribution Holdings. All rights reserved.'),
    ('Service',
     'Services'),
    ('Project',
     'Clients'),
    ('Blog',
     'Insights'),
    ('Start Project',
     'Request Quote'),
    ('Book a Call',
     'Talk to Us'),
    ('View Service',
     'Our Services'),
    ('Explore Air Freight',
     'Explore Warehousing'),
    ('Track a Shipment',
     'Track an Order'),
    ('View All Project',
     'All Client Programmes'),
    ('See More Blogs',
     'More Insights'),
    ('View Project',
     'Read the Story'),
    ('Get a Quote',
     'Get a Quote'),
    ('3.5+million satisfied customers',
     '4.200+ delivery points weekly'),
    ('Global freight forwarding blind.',
     'From our racks to your shelves.'),
    ('Freight changes hands',
     'Product changes hands'),
    ('A shipment may pass through multiple carriers, terminals, customs authorities, and distribution centers before it reaches its final destination. Every handoff creates another opportunity for delays, missing information, and unexpected costs.',
     'Between your production line and the shelf, a product passes through storage, picking, packing, regional transfer and the delivery van. Every handover is another chance for stock-outs, wrong quantities and unexpected cost.'),
    ('Freight changes hands. Responsibility should not.',
     'Product changes hands. Responsibility should not.'),
    ('coordinate capacity',
     'coordinate stock'),
    ('communicate matters',
     'communicate clearly'),
    ('moving parts',
     'moving parts'),
    ('Total Global Users',
     'Orders delivered last year'),
    ('Worldwide Customer',
     'Nationwide retail coverage'),
    ('68+ Country observation',
     '38+ regional distribution hubs'),
    ('No hidden fees or suppries',
     'No hidden fees or surprises'),
    ('Customized design plans',
     'Coverage plans built per brand'),
    ('One logistics for every of the journey.',
     'One distribution partner for the whole journey.'),
    ('From urgent air cargo to long-term warehousing and final-mile delivery, our services can work independently or as one connected supply-chain solution.',
     'From bulk storage and order picking to route delivery and in-store execution, our services can run on their own or as one connected distribution programme.'),
    ('Air Freight',
     'Warehousing & Storage'),
    ('Flexible airport-to-airport and door-to-door solutions for urgent, high-value, and time-sensitive shipments.',
     'Racked, ambient and temperature-controlled storage with batch, lot and expiry tracking for fast-moving consumer goods.'),
    ('Ocean Freight',
     'Order Fulfilment'),
    ('Reliable FCL, LCL, consolidation, and port-to-door shipping for global import and export operations.',
     'Picking, packing, labelling and consolidation for retail orders, wholesale pallets and direct-to-consumer parcels.'),
    ('Road Freight & Trucking',
     'Route Delivery & Distribution'),
    ('Regional and cross-border FTL, LTL, and dedicated trucking services built around your schedule.',
     'Fixed-route and on-demand delivery to supermarkets, independent stores, pharmacies and HoReCa, on your calendar.'),
    ('Warehousing & Distribution',
     'Retail Execution & Merchandising'),
    ('Secure storage, inventory coordination, cross-docking, order preparation, and regional distribution.',
     'Shelf placement, planogram checks, promotional set-up and field feedback from the stores we deliver to.'),
    ('Tell us what you are moving, where it needs to go, and when it needs to arrive.',
     'Tell us what you distribute, which channels you sell through, and how often shelves need refilling.'),
    ('Coordinate',
     'Set Up'),
    ('We compare transport modes, carrier points to create a practical shipping plan.',
     'We map storage, stock levels and delivery routes into a coverage plan that fits your demand.'),
    ('Moving',
     'Operate'),
    ('From pickup and export documentation to customs & and keep your team informed.',
     'Goods in, put-away, picking and dispatch run daily while your team keeps full visibility of stock.'),
    ('Delivery',
     'Deliver'),
    ('Monitor',
     'Review'),
    ('Follow your shipment in real time with status updates and delivery notifications.',
     'Track fill rate, delivery accuracy and stock coverage, and adjust the plan every month.'),
    ('Know where your freight stands—and what happens next',
     'Know where your stock stands — and what moves next'),
    ('Real-time milestone updates',
     'Live stock levels per warehouse'),
    ('Estimated arrival visibility',
     'Delivery windows per route'),
    ('Document status',
     'Batch, lot and expiry status'),
    ('Proof of delivery',
     'Proof of delivery per store'),
    ('Dedicated support contact',
     'Dedicated account contact'),
    ('Access shipment milestones, estimated arrival information, documents, and status updates in one clear view. When plans change, your team receives the information needed to respond quickly.',
     'See stock on hand, orders in picking, dispatched loads and delivered drops in one clear view. When demand shifts, your team gets what it needs to reorder and reroute quickly.'),
    ('One Accountable Team',
     'One Accountable Team'),
    ('Instead of managing disconnected providers, you receive one primary team responsible for coordinating the complete shipment journey.',
     'Instead of a warehouse operator, a carrier and a merchandising agency, you get one team accountable for the product from goods-in to shelf.'),
    ('Proactive Communication',
     'Proactive Communication'),
    ('We communicate key milestones, risks, and required decisions before they become urgent operational problems.',
     'We flag low stock cover, route pressure and delivery exceptions before they turn into empty shelves.'),
    ('Solutions Built Around Your Cargo',
     'Built Around Your Product'),
    ('Route, service level, transport mode, and handling requirements are selected around your priorities—not a fixed package.',
     'Storage type, order cut-off, delivery frequency and handling rules are set around your product and your channels — not a fixed package.'),
    ('Scalable Capacity]',
     'Capacity That Scales'),
    ('Support a one-time shipment, seasonal demand, or an ongoing international supply chain through the same operational network.',
     'Handle a single product launch, a seasonal peak or year-round national distribution through the same operational network.'),
    ('Logistics shaped your industry operates.',
     'Distribution shaped around how your category sells.'),
    ('One of the  Best Accountable Team',
     'One Accountable Distribution Team'),
    ('Representing clients in disputes with a focus on strategy, evidence, and outcome.',
     'One team owning storage, fulfilment and delivery, with a single point of contact for your brand.'),
    ('Clear Shipment Visibility',
     'Clear Stock Visibility'),
    ('Select air, ocean, road, rail, or multimodal transportation, capacity, and delivery priorities.',
     'See stock on hand, stock in transit and stock at store level, with reorder points you control.'),
    ('Flexible Transport Options',
     'Flexible Delivery Options'),
    ('Receive milestone updates, document status, estimated arrival information, communication.',
     'Choose pallet, case or unit delivery, on fixed routes or on demand, with the frequency each channel needs.'),
    ('Scalable Capacity with shipment',
     'Capacity That Scales With Demand'),
    ('Support one-time shipments, seasonal demand, or an ongoing international supply chain.',
     'Cover a launch, a seasonal peak or continuous nationwide replenishment on the same network.'),
    ('Better coordination creates measurable results.',
     'Better distribution creates measurable results.'),
    ('Supply Chain Optimization',
     'Grocery Retail Replenishment'),
    ('Inventory, fulfillment, distribution, and final-mile coordination for growing retail operations.',
     'Daily replenishment, shelf-ready packing and route delivery for a fast-growing grocery brand.'),
    ('Transportation Efficiency',
     'Pharmacy Distribution'),
    ('Time-sensitive inbound freight and parts distribution that help production and service networks stay moving.',
     'Temperature-controlled storage and batch-tracked delivery to a national pharmacy network.'),
    ('Coordinated transportation and storage solutions for sensitive, high-volume, and time-critical goods',
     'Storage and distribution for high-volume, time-critical and temperature-sensitive goods'),
    ('E-Commerce Logistics Excellence',
     'D2C & Marketplace Fulfilment'),
    ('Inbound materials, project cargo, and outbound distribution designed around production schedules.',
     'Unit picking, branded packing and next-day parcel dispatch for online and marketplace orders.'),
    ('What our customer saying about us?',
     'What our clients say about us'),
    ('Director of Operations, RetailPeak',
     'Head of Operations, RetailPeak'),
    ('Operations Director',
     'Commercial Director'),
    ('Supply Chain Manager',
     'Supply Chain Manager'),
    ('Flexible Pricing plan',
     'Flexible distribution plans'),
    ('Freight Transportation',
     'Starter Distribution'),
    ('Essential brand identity design (logo, color, typography).',
     'Shared warehouse space with pallet-based storage.'),
    ('Basic UI/UX design for landing page or app prototype.',
     'Order picking and packing, up to 500 order lines per month.'),
    ('Simple creative consultation (up to 2 sessions).',
     'Weekly delivery on two regional routes.'),
    ('Fast turnaround time for quick launch.',
     'Next-day dispatch on orders placed before cut-off.'),
    ('Easy revision process (up to 2 revisions).',
     'Monthly stock and delivery reporting.'),
    ('Full brand identity system (logo, colors, typography, visual elements).',
     'Dedicated racked space, ambient and chilled storage.'),
    ('UI/UX design for website or app (multi-page design).',
     'Full fulfilment for retail, wholesale and D2C orders.'),
    ('Creative campaign concept & social media kit.',
     'Daily delivery across your priority regions.'),
    ('Strategic creative consultation (up to 4 sessions).',
     'Replenishment planning with agreed stock cover targets.'),
    ('More flexibility on revisions (up to 4 revisions).',
     'Batch, lot and expiry tracking on every movement.'),
    ('Project timeline tailored to your business goals.',
     'Account manager and monthly performance review.'),
    ('Customs & Final Delivery',
     'National Distribution'),
    ('Comprehensive brand identity & guidelines (logo, visual system, brand assets).',
     'Multi-hub storage across the national network.'),
    ('Advanced UI/UX design for multi-platform products.',
     'Unlimited order lines across every sales channel.'),
    ('Full creative campaign development (social, digital ads, and offline-ready).',
     'Nationwide route delivery, including cold chain.'),
    ('Dedicated project manager & priority support.',
     'Dedicated account team and priority exception handling.'),
    ('Unlimited creative consultation during project.',
     'Retail execution: shelf checks, planograms, promotions.'),
    ('Unlimited revisions during project timeline.',
     'Reverse logistics: returns, recalls and expired stock.'),
    ('Deep market & competitor analysis included.',
     'Sell-out reporting per store and per SKU.'),
    ('We understand that building a company — and finding the right partner — raises a lot of questions.',
     'Choosing who handles your product raises a lot of questions. Here are the ones we hear most.'),
    ('Yes, our AI systems are designed to integrate seamlessly with popular business tools, CRMs, communication platforms, and workflow management systems.',
     'We store, pick, pack and deliver physical goods: food and beverage, household and personal care, pharmacy and para-pharmacy, and light industrial supplies. We also handle shelf placement and returns for the stores we serve.'),
    ('2. How quickly will I receive a quote?',
     '2. How quickly will I receive a quote?'),
    ('5. What information is needed for a freight quote?',
     '5. What do you need from me to price a distribution plan?'),
    ('Our Blog & insights',
     'Insights from the warehouse floor'),
    ('Warehouse & Inventory Solutions',
     'Warehouse & Inventory'),
    ('Freight & Transportation',
     'Route Delivery'),
    ('Logistics Technology',
     'Distribution Technology'),
    ('Industry News & Trends',
     'Retail News & Trends'),
    ('Expert Tips & Guides',
     'Practical Guides'),
    ('Supply Chain Management',
     'Supply Chain Management'),
    ('Technology & Digital Transformation',
     'Technology & Automation'),
    ('Receive practical logistics guidance and company updates in your inbox.',
     'Practical distribution guidance and GDH updates, straight to your inbox.'),
    ('Receive practical logistics guidance',
     'Practical distribution guidance'),
    ('and company updates in your inbox.',
     'and GDH updates in your inbox.'),
    ('Our Service',
     'Company'),
    ('Case Study',
     'Clients'),
    ('350 7 Avenue SW, ',
     'Str. Depozitelor 24, '),
    ('Calgary, AB T2P ',
     'Hala D2, Sector 2, '),
    ('3N9, Canada',
     'București, România'),
    ('+0076 20 7946 0857',
     '+40 21 300 40 50'),
    ('partners@mastercare.com',
     'office@gdh-group.com'),
    ('Freight Forwarding &amp; Logistics Services',
     'Distribution Services'),
    ('Freight Forwarding & Logistics Services',
     'Distribution Services'),
    ('Explore air, ocean, road, rail, 3PL, and last-mile delivery services designed to keep global supply chains moving.',
     'Warehousing, order fulfilment, route delivery, cold chain and retail execution — services designed to keep your product on the shelf.'),
    ('A highly accountable team',
     'A highly accountable team'),
    ('Alternative dispute resolution',
     'Returns and recall handling'),
    ('Teams in this process.',
     'One team across the whole flow.'),
    ('Full shipment visibility throughout',
     'Full stock visibility throughout'),
    ('Clear and transparent shipment',
     'Clear and transparent stock data'),
    ('End-to-end flexible transport',
     'End-to-end flexible delivery'),
    ('Altern solutions for every Transfarant',
     'A delivery model for every channel'),
    ('Seamless flexible transport',
     'Seamless, flexible delivery'),
    ('Flexible and scalable capacity',
     'Flexible and scalable capacity'),
    ('Pre-litigation advisory and case assessment',
     'Returns triage and stock recovery'),
    ('Dispute Resolution &amp; Litigation',
     'Returns &amp; Reverse Logistics'),
    ('Dispute Resolution & Litigation',
     'Returns & Reverse Logistics'),
    ('Professional legal support.',
     'Professional returns handling.'),
    ('Strategic dispute resolution and litigation',
     'Structured returns, recalls and credit notes'),
    ('Effective solutions for dispute resolution',
     'Effective handling of returned and expired stock'),
    ('Freight &amp; Supply Chain Case Studies',
     'Client Distribution Programmes'),
    ('Freight & Supply Chain Case Studies',
     'Client Distribution Programmes'),
    ('Request a Freight &amp; Logistics Quote',
     'Request a Distribution Quote'),
    ('Request a Freight & Logistics Quote',
     'Request a Distribution Quote'),
    ('/Case Study',
     '/Clients'),
    ('/Blog',
     '/Insights'),
    ('Brand Identity',
     'Grocery Retail'),
    ('UI Design',
     'Pharmacy'),
    ('Transportation &amp; Freight',
     'Route Delivery'),
    ('Transportation & Freight',
     'Route Delivery'),
    ('E-Commerce Logistics',
     'D2C &amp; Marketplace'),
    ('International Logistics',
     'Industrial Supply'),
]

# inlocuiri de subsir, aplicate doar in noduri de text si atribute alese
SUBSTR = [
    ('“Before Frevanta', '“Before GDH'),
    ('“Working with', '“Working with'),
    ('“Frevanta', '“GDH'),
    ('Frevanta', 'GDH'),
    ('tel:+00762079460857', 'tel:+40213004050'),
    ('mailto:partners@mastercare.com', 'mailto:office@gdh-group.com'),
]
